GET http://localhost:8080/register

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "Bryce",
    "password": "Password"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "name": "Bryce",
    "password": "Password"
}